enjoy-digital/litedram

- litedram/core/bankmachine.py
When the next row to be accessed is different we can embed the precharge command into the read by toggling A10.  This work does that and saves us some command bus traffic.
Its not as efficient area-wise as it could be.  If we could peek into the next cmd_buffer value then we could eliminate the FIFO and row_last registers I added.
Timing was validated via simulation with a Micron Bus Functional model.
> Add auto-precharge support

- litedram/modules.py
WIP, some reliability issues when testing with ECP5 Versa hat
> modules: Add AS4C32M16 32Mx16 SDRAM

- litedram/modules.py
Added MT40A612M16 and MT16KTF1G64HZ
> Additional DDR3 and DDR4 SDRAMModules

- examples/arty_config.py
- examples/genesys2_config.py
- examples/litedram_gen.py
- examples/nexys4ddr_config.py
Signed-off-by: Gabriel Somlo <gsomlo@gmail.com>
[florent@enjoy-digital.fr: use add_csr_master, fix csr_port.dat_r typo]
> examples/litedram_gen: allow direct access to CSR (I/O) registers

- litedram/init.py
> Fix broken LPDDR support.

- examples/arty.yml
- examples/genesys2.yml
- examples/versa_ecp5.yml
- litedram/gen.py
Initial implementation to support ECP5 target for the litedram standalone core generator.
Fixes #106.
> WIP: litedram_gen: add ecp5 support

- litedram/phy/model.py
This PR adds support for initializing contents of `SDRAMPHYModel` which can greatly help with simulations.
This still needs some adjustments because LiteDRAM uses `ROW_BANK_COL` order and I initially went with simpler `BANK_ROW_COL` order. At this point data is visible in simulation but it is all over the place.
Closes #102
> phy/model: add support for initializing memory from file

- litedram/phy/model.py
It appears that DDR2/DDR3 issues in enjoy-digital/litex#355 were caused by write data and write control signals being out of sync.
After delaying the control signals connected to `BankModel` by `write_latency` cycles DDR2 and DDR3 memories work correctly in simulation
> phy/model: simulate write latency

- litedram/phy/model.py
There are some limitations with current DRAM memory initialization, this PR aims to fix those issues
Currently known issues/limitations:
> phy/model: init fixes

- litedram/phy/model.py
This PR adds support for initializing 8/16-bit SDR modules
> phy/model: add support for 8/16-bit wide SDR memory init

- litedram/frontend/bist.py
Closes https://github.com/enjoy-digital/litedram/issues/134
> Benchmark: use Memory instead of Case for custom access pattern

- test/run_benchmarks.py
This is to solve the problem of unbound disk usage when running benchmarks in parallel. Previously each benchmark case was being run in a separate directory, but this does not scale well when running a lot of benchmarks (~20MB/benchmark). Now we use one directory per process, so that build directories are reused.
> Benchmark: reduce disk usage when running benchmarks in parallel

- litedram/phy/model.py
This PR updates the `tREFI` verifier to be less strict and check only if average `tREFI` constraint was satisfied. Previous test that checked if there was at most `tREFI` delay between `REF` commands is only enabled in verbose mode.
Additionally this adds checks for refresh postponing that is supported from DDR onwards.
It is also worth noting that this seems to fix the `tREFI` issues mentioned in litex-hub/linux-on-litex-vexriscv#103 which could mean that the current model is too strict
> Update tREFI verifier

- test/summary/summary.html.jinja2
Closes https://github.com/enjoy-digital/litedram/issues/149.
> Benchmarks: fix wrong sorting in benchmarks summary (#149)

- test/run_benchmarks.py
> test/benchmarks: add memtype to summary (#151)

- litedram/modules.py
This PR adds definition for a module that I'm using in litex-hub/litex-boards#47
> modules: add KVR21SE15S8/4 SO-DIMM

- CONTRIBUTORS
- litedram/phy/model.py
- test/run_benchmarks.py
Signed-off-by: Karol Gugala <kgugala@antmicro.com>
Signed-off-by: Mateusz Holenko <mholenko@antmicro.com>
> Fix copyrights

- litedram/gen.py
This is mostly copied over [from liteeth](https://github.com/enjoy-digital/liteeth/blob/32d4af1148d59939fdf04b4ba319c83427b698c3/liteeth/gen.py#L268).
> Allow specifying builder arguments for standalone generator

- test/test_ecc.py
Adds tests for ECC from https://github.com/enjoy-digital/litedram/issues/156.
> Add unit tests for ECC

- test/common.py
- test/test_fifo.py
This PR along with https://github.com/enjoy-digital/litedram/pull/170 would close https://github.com/enjoy-digital/litedram/issues/156.
> Add tests for litedram.frontend.fifo

- test/common.py
- test/test_bankmachine.py
- test/test_crossbar.py
Closes https://github.com/enjoy-digital/litedram/issues/155.
This PR adds core.crossbar tests of address mapping, arbitration, locking and different port types. It also includes a small fix of core.bankmachine tests.
> Add litedram.core.crossbar tests

- litedram/phy/usddrphy.py
Signed-off-by: David Shah <dave@ds0.me>
> usddrphy: Support for x4 chip based DIMMs

- litedram/init.py
- test/reference/ddr3_init.h
- test/reference/ddr4_init.h
- test/reference/sdr_init.h
For #https://github.com/enjoy-digital/litex/pull/530.
> Init: Generate DFII defines in sdram_phy.h

- litedram/dfii.py
(needs corresponding sdram.c fix in litex)
Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
> Default to HW control for sim

- litedram/phy/lpddr4/README.md
This is a modified version of https://github.com/enjoy-digital/litedram/pull/224#issuecomment-778236507 made into a README.
> lpddr4: add a local README with a summary of the code

- litedram/frontend/adapter.py
Realized I made a minor typo in the version submitted for a pull request. This exact version is now verified in hardware.
Signed-off-by: Andrew Butt <andrewb1999@gmail.com>
> Fix adapter reverse typo

- litedram/init.py
Currently `generated/sdram_phy.h` includes `sdram_dfii_pix_*data_addr` as variables (arrays). This prevents the header from being included in more than one .c file, because this results in multiple definitions of the variable. This PR replaces these variables using inline functions which look like this:
```c
static inline unsigned long sdram_dfii_pix_wrdata_addr(int phase){
switch (phase) {
case 0: return CSR_SDRAM_DFII_PI0_WRDATA_ADDR;
case 1: return CSR_SDRAM_DFII_PI1_WRDATA_ADDR;
case 2: return CSR_SDRAM_DFII_PI2_WRDATA_ADDR;
case 3: return CSR_SDRAM_DFII_PI3_WRDATA_ADDR;
case 4: return CSR_SDRAM_DFII_PI4_WRDATA_ADDR;
case 5: return CSR_SDRAM_DFII_PI5_WRDATA_ADDR;
case 6: return CSR_SDRAM_DFII_PI6_WRDATA_ADDR;
case 7: return CSR_SDRAM_DFII_PI7_WRDATA_ADDR;
default: return 0;
}
}
``` …
> init: generate sdram_phy.h in a way that allows to include it in multiple units

- litedram/phy/lpddr4/commands.py
- litedram/phy/lpddr4/sim.py
- litedram/phy/lpddr4/simphy.py
- litedram/phy/lpddr4/simsoc.py
- litedram/phy/sim_utils.py
- litedram/phy/utils.py
This is a follow-up to https://github.com/enjoy-digital/litedram/pull/257. It only moves some code around to minimize the amount of changes that will be visible in a PR that adds LPDDR5.
> LPDDR4 minor refactor 

- litedram/gen.py
The various UART bits in there need to be skipped
Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
> Fix generation with no CPU

- litedram/phy/s7ddrphy.py
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
> phy: s7: add DDR4 memtype as well

- litedram/modules.py
Have tested this module on my PBlaze3 Kintex-7 board.
> add support for MT41K256M8 module

- litedram/init.py
- litedram/phy/s7ddrphy.py
This PR fixes the DDR4 mode for the S7 PHY
There is the addition of:
- x4 mode (instead of the default x8)
- bank group signals addition
- `act_n` signal addition
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
> s7phy: fix DDR4 mode

- litedram/phy/__init__.py
- litedram/phy/gw5ddrphy.py
It's a simple gw2ddrphy copy with fix for some primitives
> phy/gw5ddrphy: introducing GW5A DDR phy

- litedram/modules.py
> modules: add Insignis NDS36PT5
