litedram/common.py, litedram/core/bankmachine.py, litedram/core/multiplexer.py, litedram/modules.py
Issues:
tCCD was per bank while the timing constraint is per rank.  I moved this to the multiplexer
tRRD was not implemented at all.  It was usually unnecessary with a 1:4 controller.
tFAW was per bank while the timing constraint is per rank.  As with tCCD it is moved to the multiplexer
=> Fix timing issues (tRRD, tCCD, and tFAW)

litedram/common.py, litedram/core/multiplexer.py, litedram/frontend/crossbar.py
This pull request implements the following:
- Configurable out of order (per port)
- Write bank to allow the interface to reconstruct the actual order of operations
- Tested with one out of order port and one in order
- Prints a warning that reordering is still experimental
=> Out of Order Completion

litedram/core/bankmachine.py, litedram/core/multiplexer.py, litedram/core/refresher.py
This work re-enabled auto-precharge.  To truly shine it needs to be combined with out of order support (and so this PR is dependent upon the Out of Order PR).  I've reworked the timing which should hopefully fix the problems we were having before.
Given our previous problems with this change and my lack of hardware to test with this should be treated with extra scrutiny.
=> Auto precharge

litedram/core/multiplexer.py
Some timings are off by 1 core cycle.
=> Fix failing timing

litedram/core/bankmachine.py, litedram/core/multiplexer.py
This was originally written as a fix for the 1:2 efficiency bug but it was not the cause.
However I think this refactor is necessary to do smarter reordering in the future.  Right now when cmd.ready is false a bank machine will not assert the valid signal and therefore the multiplexer has no information on which bank to choose next.  Making the valid signal independent of ready is also a cleaner design.
This change does improve one scenario: When a command comes in while we're waiting for tCCD in a different bank than the current (and all other banks are idle).
NOTE: This is a pull request to the new staging branch.  Additional testing is needed before up-streaming to master but I want to code review it.  It simulates correctly.
=> Bank valid/ready refactor

litedram/common.py, litedram/core/bankmachine.py, litedram/modules.py
I'm getting these timing failures on random sequences that are only across 2 banks.  More rarely with wider patterns.
=> This adds support for tRC timing parameters

litedram/core/bankmachine.py
This updates the formula so it doesn't use hardcoded numbers.  I believe it correctly accounts for the total end-to-end write time, however the datasheet mentions a timing parameter AL that I don't see us use anywhere.  The latency between the command and start of transmission of the write data is supposed to be CWL + AL.
Tested with the 1:2 and 1:4 Phys.
=> Update the write-to-precharge timings so it works with 1:2

litedram/common.py, litedram/frontend/crossbar.py
It's really hard to meet timing in the 1:2 controller.  With the reordering controller its not possible to register the wdata input in all cases as its dependent on the wbank parameter.  This optional feature allows the wbank and ready signals to be asserted N cycles early to allow registering of the data bus after MUXing the bank.
N must be less than CWL, and will usually just be 1.  The setting is per master.
=> Add a latency parameter so wdata can be registered

litedram/phy/ecp5ddrphy.py
Works reliably for me at 50MHz, 75MHz and 100MHz
=> ecp5ddrphy: Shift read position forwards to fix higher frequencies

litedram/sdram_init.py
Enable support for future 64-bit architectures: "unsigned long" matches the native pointer size of each architecture (32 vs. 64 bits, respectively), as opposed to "unsigned int" which is always 32 bits, and therefore won't be able to store 64-bit addresses.
=> sdram_init: use "unsigned long" for address values

litedram/modules.py
This is the chip that is actually on my Arty A7 100T (there is no mention of this chip in the Arty reference, which claims it is MT41K128M16JT-125).
I just added the speed class that is on my board, adding others with the intended design might be an issue because I think some of the "technology timings" actually depend on the speed class.
=> modules/ddr3: add IS43TR16128B_125K

litedram/modules.py
The IS42S16320D-7TL 32Mx16 512Mb SDRAM chips are used in Terasic DE1-SoC and Terasic DE2-115
FPGA development boards.
=> modules: SDRAM: add IS42S16320 support

litedram/phy/s6ddrphy.py
It looks like 50e1d478db66570d68316525ecb37bfc434f25c3 missed this one.
=> PhySettings: set missing databits parameter for S6QuarterRateDDRPHY

litedram/frontend/dma.py
I propose to expose the rsv_level of LiteDRAMDMAReader as an attribute.
This change does not break anything and allows for example to start burst read operations only when the FIFO has enough data:
dma_reader = LiteDRAMDMAReader(...)
read_trigger.eq(dma_reader.rsv_level >= video_line_width)
=> dma: expose reservation level in the reader

litedram/modules.py
Hi,
this adds support for the Micron MT47H32M16 family of DDR2 RAMs.
They are (except for being half the size and having half the bank count) identical to the MT47H64M16 already supported, so they could also be written with less duplication.
=> modules: Add support for Micron MT47H32M16 DDR2 RAM

litedram/frontend/axi.py, litedram/frontend/wishbone.py
Rocket's 'mem_axi' and LiteDRAM's native ports both happen to have the same (64-bit) data width, (EDIT: true only on the nexys4ddr -- on the versa, liteDRAM is 128bit!) and therefore can be connected together using LiteDRAMAXI2Native() (see https://github.com/enjoy-digital/litex/pull/284).
However, we should ensure that axi and native ports have the same data width, in case we ever end up trying to connect interfaces with non-matching data width!
=> frontend/[axi,wishbone]: add data_width match assertion, add base_address to LiteDRAMWishbone2Native

litedram/init.py
Use DFII_NPHASES constant (defined earlier in the file) to size the
two 'sdram_dfii_pix_[wrdata|rddata]_addr' arrays, instead of a bare
number. Additionally, ensure the first array element is indented by
a tab, same as the ones following it.
=> init: improve legibility of generated/sdram_phy.h (cosmetic)

litedram/modules.py
Add AS4C32M8SA-7TCN 32MB SDRAM used on cartridge PCB by Jacob Creedon (@jcreedon) for the [Hackaday Supercon 2019 badge](https://hackaday.io/project/167255-2019-hackaday-superconference-badge) which has an ECP5 FPGA.
These changes are from [a fork](https://github.com/mwelling/litedram) by Michael Welling (@mwelling)
In addition to @mwelling, thank you to Jacob Creedon (@jcreedon), @GregDavill, Tim Ansell (@mithro), and Sean Cross (@xobs) who all helped get Linux working on this badge.
KiCad design files by @jcreedon for the SDRAM cartridge are [available on GitHub](https://github.com/jcreedon/dram-cart/).
There is also a [shared project](https://oshpark.com/shared_projects/IQSl2lid) to order the SDRAM cartridge PCB.
Refer to [my blog …
=> add 32MB SDRAM for hadbadge

litedram/modules.py
This PR adds support for the H5TC4G63CFR DDR3 RAM module used on the enclustra KX2 board as specified here:
https://www.enclustra.com/en/products/fpga-modules/mercury-kx2/
=> ADD: KX2 DDR3 module

litedram/phy/model.py
It appears that only thing that prevents us from using this model with DDR4 memories is `burst_length` value, initially I've set it to 2 as this value is used by all DDR memory types.
=> phy/model: add burst_length value for ddr4 memories

test/benchmark.py
This adds arguments to configure BIST from command line. 
Using `int(_, 0)` to also parse hex values.
Closes https://github.com/enjoy-digital/litedram/issues/108.
=> test: add command line arguments for BIST base/length/random

test/run_benchmarks.py
The script runs as benchmarks defined in a list of configurations, parses their output and produces summary of bandwidth/performance.
Are the efficiency calculations correct? 
Numbers of ticks in BIST generator/checker are counted per dma write to the LiteDRAM port, so I am dividing by the data width.
Things to improve:
* the list of configurations could be loaded from a file
* summary by single metric (e.g. model/bist_length)
* add plotting summary (I will probably use matplotlib for that)
This would close https://github.com/enjoy-digital/litedram/issues/109.
=> Add a script for running LiteDRAM benchmarks

test/benchmarks.yml, test/run_benchmarks.py
Closes https://github.com/enjoy-digital/litedram/issues/119.
The script now loads benchmarks configuration from a YAML file and allows to optionally filter tests based on their name using regex. 
I've put an example YAML in `test/`. Is it ok? Or maybe it should go to `examples/benchmarks`?
I also moved to relative imports in https://github.com/enjoy-digital/litedram/commit/096de78c63c5c5543453b014f830202774f098eb because `python setup.py test` was trying to load the file and failed due to import problem. This means that now the script has to be run with `python -m test.run_benchmarks <args>`. As another option we could change `python setup.py test` in Travis configuration to `python -m unittest`, which seems to avoid touching files that do not start with `test_`.
=> Load benchmark configuration from YAML

test/run_benchmarks.py
This adds option to plot the results of benchmarks using Matplotlib (closes https://github.com/enjoy-digital/litedram/issues/120).
The text summary has also been cleaned up a bit.
Plotting is enabled with `--plot` switch. 
By default plots are generated using non-GUI backed so `matplotlib` should be the only dependency when not using any GUI.
I've added an option to store intermediate results (output of individual benchmarks) in a file, so that it is possible to re-run the benchmarks fast with different summary (and possibly filtering results). It is stored using `pickle`.
So additional Python dependencies are `matplotlib` and `pickle`, but the script can run without them if not used. Should we list them in `setup.py` as [optional …
=> Add plotting of benchmark results

litedram/phy/model.py
This PR removes code responsible for word order reversing as it is no longer needed since adding `l2_reverse` and additionally does a general cleanup by making a separate method from bank init code to only run it when needed
Closes #102
=> phy/model: cleanup the memory init code

litedram/phy/model.py
This fixes an issue where init data was being overwritten when using configuration using 32-bit wide `BankModel` memories, ie. default SDRAM configuration.
This should help with latest issue from litex-hub/linux-on-litex-vexriscv#84
=> phy/model: fix case when not converting init data width

test/benchmark.py, test/benchmarks.yml, test/run_benchmarks.py
This adds option to measure read/write latency. Latency measurements are triggered by `--bist-length 1` and displayed/plotted separately.
Closes https://github.com/enjoy-digital/litedram/issues/112.
This also includes modification to use JSON instead of pickle as suggested in https://github.com/enjoy-digital/litedram/issues/110.
=> Add Write/Read latency measurement

litedram/modules.py
Fixes error:
```
$ litex_sim --with-sdram --sdram-module MT18KSF1G72HZ
Traceback (most recent call last):
File "bin/litex_sim", line 11, in <module>
load_entry_point('litex', 'console_scripts', 'litex_sim')()
File "litex/litex/tools/litex_sim.py", line 301, in main
**soc_kwargs)
File "litex/litex/tools/litex_sim.py", line 187, in __init__
sdram_module     = sdram_module_cls(sdram_clk_freq, sdram_rate)
File "litedram/litedram/modules.py", line 65, in __init__
File "litedram/litedram/modules.py", line 110, in ns_to_cycles
TypeError: can only concatenate tuple (not "float") to tuple
```
=> modules: MT18KSF1G72HZ: use float as tWR value

test/run_benchmarks.py
These changes should significantly speed up the process of running benchmarks and generating summary:
1. We can run benchmarks as parallel jobs using `multiprocessing`, by default `os.cpu_count()` is used, but it can be controller with `--njobs`.
2. By default, we continue running even if some benchmarks fail, and a summary of failures will be displayed at the end. `--fail-fast` can be specified if we want to exit on any error.
3. Removed the code that instantiated `LiteDRAMBenchmarkSoC`, as it was taking a lot of time to do it for each configuration.
4.  I've fixed problem with plots being unreadable when there are too many entries; now we just increase figure size as needed.
About 3:
`LiteDRAMBenchmarkSoC` was only used to retrieve clock frequency and interface data width. Now data …
=> Improve speed of benchmark runner

litedram/frontend/bist.py, test/benchmark.py, test/benchmarks.yml, test/gen_config.py, test/run_benchmarks.py, test/test_bist.py
Closes https://github.com/enjoy-digital/litedram/issues/133.
Partially implements https://github.com/enjoy-digital/litedram/issues/114 (still single generator and checker).
I've added random address generation as suggested in https://github.com/enjoy-digital/litedram/issues/133, but limiting values makes them not unique, so to actually use such generator, I had to also implement simultaneous write/read.
To allow for alternating write/read patterns, I added `run` and `ready` signals to generators and checkers. When `run` is low, generator will stop writing/reading and go to `WAIT` state until `run` is high again. To have the previous behaviour, we can just set `run.eq(1)`, and by cross-connecting the signals between generator and checker, we can make them perform alternating write/read. …
=> Benchmark: add simultaneous Write/Read and random address generation

.sim-test.py, .travis.yml
This PR adds a new stage to Travis CI, which runs litex_sim and linux-on-litex-vexriscv simulations for each sdram module.
=> Add simulations to Travis CI

litedram/frontend/bist.py, test/benchmark.py, test/benchmarks.yml, test/gen_config.py, test/run_benchmarks.py
Closes https://github.com/enjoy-digital/litedram/issues/114.
This adds an option to specify `--num-generators` and `--num-checkers` for `benchmark.py` to have more than one generator/checker. 
Max value of ticks is used as the final benchmark result (for generator ticks, checker ticks and checker errors). In the final bandwidth/efficiency calculations the number of data is multiplied according to the number of generators/checkers.
I've also updated `gen_config.py`. It is useful for testing purpose, but product of all options quickly results in over 1000 benchmarks, so for real benchmarks we should most likely specify configurations by hand anyway.
=> Benchmark: use variable number of BIST generators/checkers

litedram/phy/model.py
This PR adds a module to PHY model that will check DFI interface timings against timings specified in `modules.py`.
At this point only a limited subset of bank commands is tested
=> phy/model: add basic timing violation checker

litedram/phy/model.py
This fixes litex-hub/linux-on-litex-vexriscv#104
=> phy/model: fix memory addressing issues in some configurations

.travis.yml, test/benchmark.py, test/run_benchmarks.py, test/summary/summary.css, test/summary/summary.html.jinja2
This PR adds benchmarks summary in HTML format and deployment to GitHub Pages.
Closes https://github.com/enjoy-digital/litedram/issues/110.
**Travis:**
Benchmarks are being run in Travis and deployed using GitHub Pages. The results are stored on the `gh-pages` branch. We would then need to [enable GitHub Pages in repo settings](https://help.github.com/en/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site) for `enjoy-digital/litedram` and configure it to use `gh-pages` branch. The results should then appear at [enjoy-digital.github.io/litedram/](https://enjoy-digital.github.io/litedram/).
[Here](https://docs.travis-ci.com/user/deployment/pages/#setting-the-github-token) is some more information about Travis/gh-pages. 
Options used in `.travis.yml`: …
=> Benchmarks: Generate HTML summary and deploy it from Travis

.travis.yml, test/run_benchmarks.py
This PR adds `--heartbeat` argument that is being used in CI to print heartbeat messages every 60 seconds. 
This solves the issue mentioned in https://github.com/enjoy-digital/litedram/pull/146#issuecomment-588089239. After some tests I've found that we need to print in a child process instead of the main process, as both `stdout` and `stderr` from main process seem to be buffered by Travis. This behavior can be reproduced using:
```
python -m test.run_benchmarks test/benchmarks.yml --njobs 2 --regex 'test_[0-3]$' >/tmp/output 2>&1
```
and then reading the file, e.g. `tail -f /tmp/output`.
Another option would be to print something on `stderr` in `benchmark.py` (e.g. `argv`), as with the current solution, because of Travis buffering, we don't get real-time feedback which tests is …
=> Benchmark: Print heartbeat message during runs in Travis CI

.travis.yml, test/run_benchmarks.py
Travis normally times out a build after no output for 10 minutes. We've added a "heartbeat" to prevent this from canceling benchmarks, but it would be nice to have a timeout for some situations (e.g. when `$finish` is somehow never executed). 
In this PR I've added a `--timeout` parameter for CI builds. It seems that a single benchmark case takes ~30s, so the timeout of 9 minutes that I've added is somehow overestimated, if you want we can change it.
=> Benchmarks: add timeout parameter

litedram/common.py
S6HalfRateDDRPHY uses "dqs" instead of "dqs_p"
=> common: PHYPadsCombiner: add "dqs" to the list

test/test_bist.py
I'm working on https://github.com/enjoy-digital/litedram/issues/156. 
This PR only adds some some tests for `_LiteDRAMBISTGenerator` and I will continue to write tests for other classes, but I wanted to create the PR now, so that you can comment if it's ok or maybe you would prefer to start from other modules?
=> test: add _LiteDRAMBISTGenerator tests

test/benchmark.py, test/run_benchmarks.py
Due to https://github.com/enjoy-digital/litex/commit/b29f443fe51511df908a644a17bc2a8a1f1566cc removing the default parameter value, we need to set it explicitly.
To prevent something like this from being unnoticed (e.g. https://travis-ci.org/github/enjoy-digital/litedram/jobs/661098966?utm_medium=notification&utm_source=github_status succeeds) `run_benchmarks.py` will now fail in case all benchmarks failed.
=> Benchmarks: fix with_uart parameter

test/common.py, test/test_bist.py, test/test_dma.py
This PR adds tests for `_LiteDRAMBISTGenerator`, `_LiteDRAMPatternGenerator`, `_LiteDRAMBISTChecker`, `_LiteDRAMPatternChecker`. Test data definitions are created in `setUp` and then used as reference in different test.
It tests current pattern addressing (not https://github.com/enjoy-digital/litedram/issues/164).
If you would prefer to wait for all the BIST related tests, than I can just commit to this PR.
=> Test: add tests for BIST modules with different access patterns

test/common.py, test/test_adaptation.py, test/test_axi.py, test/test_ecc.py, test/test_wishbone.py
Adds `test_wishbone.py`  for `litedram.frontend.wishbone`.
Additionally it implements missing write-enable handling in `DRAMMemory` and `test_adaptation.py`/`test_axi.py`.
=> Add LiteDRAMWishbone2Native tests

test/common.py, test/test_adaptation.py, test/test_bist.py
Part of  https://github.com/enjoy-digital/litedram/issues/156.
This adds tests for up/down converters with different conversion ratios and for CDC.
I've also added [test_converter_up_not_aligned](https://github.com/antmicro/litedram/blob/jboc/unit-tests/test/test_adaptation.py#L199) for up-converter when the pattern is not composed of groups of `ratio` consecutive words ([example pattern](https://github.com/antmicro/litedram/blob/0afacba2ca4f1b69831bdd1b83c4cd09875cd763/test/common.py#L356)), but this currently fails so I commented out that test. Do we want to support this case in `LiteDRAMNativeWritePortUpConverter` in the future or this test case is unnecessary?
=> Add tests for litedram.frontend.adaptation

litedram/modules.py
This PR adds DDR4 SO-DIMM module that works on the ZCU104 board
This module was tested as part of litex-hub/litex-boards#49
=> modules: add MTA4ATF51264HZ DDR4 SO-DIMM

test/test_bankmachine.py
Part of https://github.com/enjoy-digital/litedram/issues/155.
This PR adds tests for `BankMachine` addressing, activation, (auto-)precharge, timings, lock and refresh.
=> Add litedram.core.bankmachine tests

litedram/core/bandwidth.py, litedram/core/bankmachine.py, litedram/core/crossbar.py, litedram/core/multiplexer.py
While writing tests for https://github.com/enjoy-digital/litedram/issues/155 I've been also filling in the documentation of these modules. This PR gathers my notes and adds missing docstrings for `core` modules. Please review them to check if there are no mistakes.
I also found that there was some dead code in `crossbar.py`. It seems that it is not needed, but correct me if I'm wrong. https://github.com/enjoy-digital/litedram/commit/1f246cbb88b9d2c286eb7f3492edbfde93fe02d7 removes these parts, and fixes indentation in the for loops.
=> Add docstrings to litedram.core modules

litedram/modules.py
RDIMM-related configuration is currently missing, as more work is required for a format for this.
=> modules: Add MTA18ASF2G72PZ DDR4 RDIMM

litedram/gen.py
This adds a few options & improvements to standalone LiteDRAM generation as used by Microwatt
=> Improve standalone cores

litedram/common.py, litedram/init.py, litedram/phy/usddrphy.py
I would appreciate some feedback on the structure, it seems like perhaps is_rdimm and drive strengths should be a module property, but I can't find a nice way of glueing that in.
This also still needs regression testing on a non-RDIMM platform too, I can do that if you want.
=> Add support for DDR4 RDIMMs

litedram/modules.py
This adds a function for parsing SPD EEPROM data in the form dumped in BIOS.
=> modules: add function for parsing SPD EEPROM dumps from BIOS firmware

litedram/gen.py, litedram/phy/model.py
(This depends on the corresponding branch in LiteX)
This allows litedram_gen --sim to be used to generate a simulated litedram model from
the same .yml file as a real synth model.
=> Allow generation of a standalone sim model

litedram/modules.py, test/test_modules.py
Makes `SDRAMModule` store `spd_data` as a class member when generating from SPD data. This can be then used to add ROM with the data and verify it at runtime in BIOS (requries LiteX PR).
This also includes some minor changes to `DDR3SPDData` parser that I made while implementing `DDR4SPDData` parser. I didn't include DDR4 parser, as I still had some errors when using it. I will add it in a separate PR when I find what was the exact problem.
=> modules/spd: save SPD data in SDRAMModule

litedram/frontend/fifo.py, litedram/gen.py, test/test_fifo.py
Closes https://github.com/enjoy-digital/litedram/issues/203
This removes the need for `read_threshold` by using `port.wdata.ready` (or `port.w.ready` for `LiteDRAMAXIPort`) to increment FIFO level. This way data is available for read only after it has been actually written to memory. The tests have been updated and `write_threshold` has also been removed as now it is not needed.
=> frontend/fifo: increase FIFO level only after data has actually been written

litedram/dfii.py
Looks like there was a typo in commit
a595fe07f25ab9c8dac3e9707aae9cca9ede0019
"dfii: simplify control using CSRFields"
Signed-off-by: Benjamin Herrenschmidt <benh@kernel.crashing.org>
=> dfii: Really default to HW control

litedram/core/controller.py, litedram/init.py, litedram/phy/__init__.py, litedram/phy/gensdrphy.py
Corresponding issue: https://github.com/enjoy-digital/litedram/issues/183
This adds a wrapper over GENSDRPHY and option to use it on ULX3S (with https://github.com/enjoy-digital/litex/pull/563 PR).
But this does not yet work correctly, I've been trying to find an error, but with no success. 
@enjoy-digital could you please take a look if I'm missing something?
=> Add HalfRate GENSDRPHY

litedram/common.py, litedram/init.py
This adds an optional argument to `add_electrical_settings()` that can enable the TDQS mode for x8 DDR3 modules. Normally this would be used when mixing x4 and x8 modules (eg: heterogenous DIMMs), but it can also serve as a workaround boards with missing or broken DM signals.
I had to add this as a workaround for the rev0 Logicbone prototypes because the DM signals on the DDR3 modules wound up floating due to a combination of layout errors. The downside of enabling TDQS mode is that the data mask signals no longer have any effect, and you can only ever write a full burst.
Given that this is a workaround for a prototype board that may not ever see the light of day, it's also okay to reject this PR.
=> Add support for TDQS mode.

litedram/frontend/adaptation.py, litedram/frontend/wishbone.py, test/common.py, test/test_adaptation.py, test/test_crossbar.py, test/test_wishbone.py
Closes https://github.com/enjoy-digital/litedram/issues/191
This PR implements the up-converter as described in https://github.com/enjoy-digital/litedram/issues/191. It combines subsequent `port_from` commands to lower the number of `port_to` commands. It allows incomplete transfers and automatically advances to next `port_to` command when command address or type (r/w) changes. It is also possible to have gaps, e.g. for 1:4 conversion we can write/read `[0x00, 0x02, 0x03], ...`. As you suggested, I used `port_from.cmd.last` instead of `port_from.flush` to indicate the end of a burst. `cmd.last` must be 1 if the last command does not form a "complete" `port_to` command.
I added unit tests for the mentioned cases and they all pass, but I seem to have some problem during `memtest` when …
=> Implement LiteDRAMNativePortUpConverter with mode="both"

litedram/init.py
Fixes `TypeError: unsupported operand type(s) for |: 'int' and 'float'`
for some clock frequencies.
=> init: Cast DDR4 RCD fine_speed to int

litedram/modules.py
The 8 meg x 8 x 4 bank variant of the existing MT48 series modules.
The chip is used in the SDRAM and HDMI add-on shields for the Alchitry MojoV3 hobbyist platform: https://alchitry.com/products/mojo-v3
=> modules: add MT48LC32M8 SDR module

litedram/gen.py
Adds `data_width` parameter in the yml configuration for user ports of types native, AXI, and Wishbone. The parameter is optional, defaulting to previous behavior.
Generation of data width converters is handled by existing functionality in crossbar.py
```
"user_ports": {
"native" : {
"type": "native",
"data_width": 32,
},
"axi" : {
"type": "axi",
"id_width": 3,
"data_width": 32,
},
"wishbone" : {
"type": "wishbone",
"data_width": 32,
}
},
```
=> Add customizable standalone user port data widths

test/test_init.py
This is a minor change, but I hope it will improve readability of errors in `test_init.py`. It will now print a diff when the files do not match. It also avoids creating the temporary file (only reads the reference file).
=> test: improve error messages when comparing files in test_init.py

litedram/modules.py, litedram/phy/model.py
This is a part of splitting https://github.com/enjoy-digital/litedram/pull/224 into smaller PRs.
This PR makes it possible to pass all timings as `(ck, ns)` tuples (here `ns` can be `None`) or just `ns` float.
=> Allow to pass all module timings in the format (ck, ns)

litedram/init.py, test/reference/ddr3_init.h, test/reference/ddr4_init.h
This is a part of splitting https://github.com/enjoy-digital/litedram/pull/224 into smaller PRs.
Requires corresponding PR in litex: https://github.com/enjoy-digital/litex/pull/791.
In LPDDR4 the write leveling mode is configured with MR2[7] instead of MR1[7]. This PR changes the way `get_sdram_phy_init_sequence` returns mode register values. Now it should return a dictionary `{mr_num: mr_value, ...}`. Instead of generating `DDRX_MR1` define we now have 3 `DDRX_MR_WRLVL_*` defines that specify the mode register changes required to enter/leave write leveling mode.
Note that `DDRX_MR_WRLVL_BIT` is the bit that gets flipped (with xor), so `DDRX_MR_WRLVL_RESET` is the state when write leveling is disabled and software just filps given bit when entering write leveling mode and writes the …
=> init: make the write leveling MR bit configurable

litedram/gen.py
Adds ability to specify a custom build name (Verilog module name) on the CLI. When using litedram in standalone mode and generating multiple DRAM interfaces, each generated litedram module needs to have a unique name otherwise they will conflict in the Verilog namespace.
=> Add module name CLI option

litedram/core/__init__.py
This is a part of changes related to https://github.com/enjoy-digital/litedram/pull/224.
LiteDRAM normally encodes Mode Register Set command using `DFIInjector`, passing mode register address as `dfi.baddress` and value as `dfi.address`. In LPDDR4 there are more Mode Registers than in other DRAMs and we need 6 bits to store the address. So when a module has only 8 banks it is not possible to issue MRS via DFIInjector this way. 
Initially I tried encoding both the address and the value in `dfi.address`,  but then I had to modify the implementation of `sdram_write_leveling_on`/`sdram_write_leveling_off` in `sdram.c` for LPDDR4 specifically. To avoid it, now LPDDR4 PHY sets bankbits to 6: https://github.com/enjoy-digital/litedram/pull/224/commits/dfd7816567bf3b6c3f6b3c8f97cc22d512c99c47#diff- …
=> core: use wider DFI address/bank if PHY requires it

litedram/core/refresher.py
Related to https://github.com/enjoy-digital/litedram/pull/224.
In LPDDR2+ and DDR5 the refresh command has two variants: per-bank and all-banks. This PR changes Refresher to always issue the all-banks variant. This should not affect other memory types, as they always refresh all banks, ignoring the address (it just must be a defined voltage level).
=> core/refresher: use A10=1 for an all-banks REF

litedram/init.py
With the previous code generated lines included Python variable names instead of integers, e.g.
```python
("ZQ Calibration start", MPC.ZQC_START, SpecialCmd.MPC, dfii_command_we|dfii_command_cs, 200),
```
which failed as these names were not being imported.
=> Fix Python header generation for LPDDR4

litedram/common.py, litedram/init.py, litedram/modules.py, litedram/phy/lpddr4/__init__.py, litedram/phy/lpddr4/basephy.py, litedram/phy/lpddr4/commands.py, litedram/phy/lpddr4/s7phy.py, litedram/phy/lpddr4/sim.py, litedram/phy/lpddr4/simphy.py, litedram/phy/lpddr4/simsoc.py, litedram/phy/lpddr4/utils.py, test/test_lpddr4.py
This adds the copyright comments, I forgot to include them in https://github.com/enjoy-digital/litedram/pull/224.
=> lpddr4: add missing copyright comments

litedram/init.py
This adds DQ-DQS training for LPDDR4 PHY. Requires https://github.com/enjoy-digital/litex/pull/884.
This PR also includes a modification in LPDDR4PHY settings that improves signal quality during reading.
=> Add DQ-DQS training for LPDDR4 PHY

litedram/frontend/adapter.py
This pull request reverses the write mask bits in the UpConverter when reverse is set to True. Without this change `wdata_converter.source.we & wdata_sel` will result in a bad write mask as wdata_converter.source.we is reversed correctly but wdata_sel is not.
Signed-off-by: Andrew Butt <andrewb1999@gmail.com>
=> Fix UpConverter reversed write mask

litedram/init.py
Sometimes initialization parameters may need to be modified to tune the DRAM performance. This change allows to pass some key settings via `phy_settings`, the same way it is done for DDR3/DDR4.
=> init/lpddr4: make some settings configurable via phy_settings

litedram/frontend/adapter.py
In the case where the input port valid signal goes low while the UpConverter is in the FILL stage, sel would continue to update. This would cause the fsm to prematurely leave the FILL stage.
Signed-off-by: Andrew Butt <andrewb1999@gmail.com>
=> Only update UpConverter sel when input valid

litedram/init.py, test/reference/ddr3_init.h, test/reference/ddr4_init.h, test/reference/sdr_init.h
The 'cdelay()' function is defined in LiteX 'liblitedram', so we
should not be using 'static' to declare it before calling it from
other C source files.
=> fix gcc warning: function used but not defined

litedram/gen.py
It looks like commit 317072a1982d ("litedram_gen: Add initial SDRAM
support (with ULX3S example)") broke building with the --sim option.
=> litedram_gen: Fix error with --sim option

litedram/modules.py
Add the AS4C128M16 DDR3L-1600 ram used on the Alchitry Au(+)
The tRFC timing is slightly worse than the MT41J128M16 which is already in litedram
Datasheet: https://www.alliancememory.com/wp-content/uploads/pdf/ddr3/Alliance%20Memory_2G%20128Mx16%20AS4C128M16D3LB-12BCN%20v1.0%20March%202016.pdf
=> Add AS4C128M16 DDR3L-1600 ram

litedram/modules.py
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
This PR adds some additional modules for the RDIMM DDR4 type, from Micron and Hynix manufacturers.
=> modules: add more RDIMM modules

litedram/gen.py
Otherwise, the `with_uart` argument is provided twice, which gives the following error:
```
Traceback (most recent call last):
File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
exec(code, run_globals)
File "/home/jf/src/litex/litedram/litedram/gen.py", line 825, in <module>
main()
File "/home/jf/src/litex/litedram/litedram/gen.py", line 812, in main
soc     = LiteDRAMCore(platform, core_config, integrated_rom_size=0x8000)
File "/home/jf/src/litex/litedram/litedram/gen.py", line 489, in __init__
SoCCore.__init__(self, platform, sys_clk_freq,
TypeError: litex.soc.integration.soc_core.SoCCore.__init__() got multiple values for keyword argument 'with_uart'
```
=> litedram_gen: Fix duplicate with_uart value when cpu_type is None.

litedram/common.py, litedram/init.py, litedram/modules.py, litedram/phy/model.py, litedram/phy/rpc/README.md, litedram/phy/rpc/basephy.py, litedram/phy/rpc/commands.py, litedram/phy/rpc/s7phy.py, litedram/phy/rpc/simphy.py, litedram/phy/rpc/simsoc.py, test/common.py, test/test_adaptation.py, test/test_wishbone.py
This PR adds a PHY for Etron RPC DRAM. The code directory structure resembles the one used for LPDDR4/LPDDR5.  The RPC PHY was actually the first of these PHYs and there are some design choices that could potentially be revised, applying the modifications from LPDDR4/5. Currently the PHY has some limitations, but it is functional and we were able to successfully use it on a modified Arty A7 board, although we were not able to reach the default Arty frequency due to hardware limitations. The current state of the PHY is described in more details in the readme under `litedram/phy/rpc/README.md`.
=> Add RPC DRAM support

litedram/modules.py
I finally came to the conclusion that although it only works well at 50MHz and 1:2 rate,
it still will be useful if that is documented.
I just realize many of the QMTech boards have the same chip, so having
it here will be good.
=> add support for Winbond W9825G6KH-6 at 50MHz 1:2 rate

litedram/modules.py
I am not sure what they mean by 8K refresh cycles.
I assumed it is 8000 not 8192, but the datasheet does not make it clear anywhere else.
This part suggests it is 8192:
=> W9825G6KH6 seems to use 8192 refresh cycles not 8000

litedram/modules.py
Signed-off-by: Alessandro Comodi <acomodi@antmicro.com>
This PR fixes some values for the hynix RDIMM module and adds the M393A2K40DB3 one.
The timing and geometry values have been confirmed by reading them from the RDIMM's EEPROM
=> modules: add other RDIMM modules

litedram/gen.py, litedram/phy/ecp5ddrphy.py
With these three changes I am able to use litedram generated verilog for a standalone build of Microwatt on an OrangeCrab 85F 0.2.
There is one remaining issue I need to still resolve,  https://github.com/enjoy-digital/litedram/commit/e52ece0b8a73eda98c1e2a259000db54703497a8  blocks userport access while memtest runs from `sdram_init` - I can't see how our  standalone build (from same `sdram.c` source) is any different, but for now I've patched it to set `ddrctrl_init_done_write(1)` pre-memtest.
=> litedram_gen fixes for ECP5

litedram/modules.py
Based off of https://www.alliancememory.com/wp-content/uploads/pdf/dram/64M-AS4C4M16SA-CI_v3.0_March%202015.pdf and confirmed working on a single device.
=> Added AS4C4M16 for Arduino MKR Vidor 4000 support

litedram/dfii.py
This PR adds another DFI Interface that can be used to inject commands from logic outside of the LiteDRAM controller.
Moreover, it adds some description of the dfi CSRs.
=> dfi: add possibility to have an external dfi injector

litedram/phy/model.py
In case of DDR4 tRFC and tREFI timings are actually dictionaries with timings specific for the chosen refresh mode.
Right now, it is impossible to simulate DDR4, because an exception happens in `DFITimingsChecker.prepare_timings` method when indexing `val` variable.
This is due to the fact, that in `DFITimingsChecker.__init__` we request timing values from the module by name, ignoring the fact that some of them (tRFC and tREFI) need to be first accessed using the chosen refresh mode.
This commit fixes this error, by properly using `key` parameter when calling `SDRAMModule.get` method to get only required timing.
If one were to fix it in `DFITimingsChecker.prepare_timings` method, it would require duplicating logic from `SDRAMModule.get` so this is a simpler and cleaner solution. …
=> Fix DFITimingsChecker for DDR4 simulation

litedram/frontend/bist.py, litedram/frontend/dma.py
Without it, software was resetting the generator too early and wrong data was being written to the RAM.
Signed-off-by: Michal Sieron <msieron@antmicro.com>
=> frontend/bist: properly signal finished writes

litedram/init.py
Define two symbols required for SPD improvements in LiteX.
They might be even useful for more than that.
=> init: Define `SDRAM_PHY_[DDR3|DDR4|...]` and `SDRAM_PHY_SUPPORTED_MEMORY`

litedram/frontend/bist.py, litedram/gen.py, test/common.py
Rework LFSR module so it is an actual LFSR and can work with larger states.
The old LFSR module, when initialized with n_state of 1024, produced an equation so large, that Vivado complained about too many tokens on the same line.
Also, by using LFSR with n_state of 1024, we can fill an entire transfer to the SDRAM.
I took LFSR coefficients from here: https://datacipy.cz/lfsr_table.pdf
Signed-off-by: Michal Sieron <msieron@antmicro.com>
=> frontend/bist: replicate LFSR output to fill the DRAM port

test/test_examples.py, test/test_lpddr4.py, test/test_lpddr5.py
For example using pytest-parallel you can greatly reduce time it takes to run all tests.
```
$ pytest --workers auto test
```
Signed-off-by: Michal Sieron <msieron@antmicro.com>
=> Make tests safe to run in parallel

litedram/phy/gw2ddrphy.py
When using `gw2ddrphy` **Gowin** tool produces bunch of warnings like:
```
WARN  (EX3073) : Port 'Q1' remains unconnected for this instance("/somewhere/build/sipeed_tang_primer_20k/gateware/sipeed_tang_primer_20k.v":10334)
[...]
WARN  (EX3670) : Actual bit length 1 differs from formal bit length 8 for port 'WSTEP'("/somewhere/build/sipeed_tang_primer_20k/gateware/sipeed_tang_primer_20k.v":10364)
```
It's also true for simulation using **verilator**
This PR add an class called `Open` to handle unconnected output ports, and uses `Constant` to specify input ports size.
=> phy/gw2ddrphy: supressing warnings about unconnected and bit length.

litedram/common.py, litedram/core/__init__.py, litedram/dfii.py, litedram/init.py, litedram/phy/usddrphy.py
VCU128 uses clam shell topology for its DRAM components. This pull request adds support for VCU128 clam shell topology.
Clam shell topology:
1. DRAM chips are on top and bottom sides of the PCB
2. There are cs_n pins for the top and the bottom half
3. Address pins are mirrored for the bottom half
See https://github.com/litex-hub/litex-boards/issues/496 for background.
=> Add support for clam shell topology

litedram/frontend/avalon.py, test/test_avalon.py
Read and write bursts are now implemented properly,
ie without gaps on the native ports.
=> frontend/avalon: properly implement bursts

litedram/core/bankmachine.py, litedram/modules.py
For larger memories, the col encoding needs to skip `A10` because that one is reserved for auto-precharge.
The remaining col encoding bits are then mapped to `A11` and higher.
I think that newer RAM generations are defining additional reserved address bits, e.g. for DDR4 `A12` is used for burst-chop. But I ignored those higher bits, as we don't have any module with that many col bits used.
=> Add MT46H128M16 and change bankmaschine to not use A10 for col addresses.

litedram/modules.py
Got it running at 90 MHz
```
__   _ __      _  __
/ /  (_) /____ | |/_/
/ /__/ / __/ -_)>  <
/____/_/\__/\__/_/|_|
Build your hardware, easily!
(c) Copyright 2012-2023 Enjoy-Digital
(c) Copyright 2007-2015 M-Labs
BIOS built on Nov  9 2023 10:28:08
BIOS CRC passed (7ebd4500)
LiteX git sha1: f3f46e8c
--=============== SoC ==================--
CPU:		VexRiscv @ 90MHz
BUS:		WISHBONE 32-bit @ 4GiB
CSR:		32-bit data
ROM:		128.0KiB
SRAM:		8.0KiB
L2:		8.0KiB
SDRAM:		16.0MiB 16-bit @ 90MT/s (CL-2 CWL-2)
MAIN-RAM:	16.0MiB
--========== Initialization ============--
Initializing SDRAM @0x40000000...
Switching SDRAM to software control.
Switching SDRAM to hardware control.
Memtest at 0x40000000 (2.0MiB)...
Write: 0x40000000-0x40200000 2.0MiB     
Read: 0x40000000-0x40200000 2.0MiB     
Memtest OK …
```
=> Add W9812G6JB SDRAM module

litedram/phy/lpddr4/commands.py, litedram/phy/lpddr5/commands.py
This fixes multiple instances of:
litedram/phy/lpddr4/commands.py:209
litedram-2023.12/litedram/phy/lpddr4/commands.py:209: DeprecationWarning: invalid escape sequence '\d'
"BA(\d+)": lambda i: self.dfi.bank[i],
=> litedram/phy/lpddr*: fix use of invalid escape sequence

litedram/core/controller.py, litedram/core/crossbar.py
This PR add ControllerSettings.bank_byte_alignment which allow to specifiy how many byte (minimum) there should be between bank address change.
This allow to align it to L2 cache sets size, which improve performances quite a bit on VexiiRiscv :
VexiiRiscv RV64GC with hadware prefetch, 256KB 4way L2, running at 100 Mhz => 
```
without this PR
Write speed: 197.1MiB/s
Read speed: 379.4MiB/s 
With this PR and 
self.add_sdram("sdram",
phy           = self.ddrphy,
module        = MT41K256M16(sys_clk_freq, "1:4"),
l2_cache_size = kwargs.get("l2_size", 8192),
controller_settings=ControllerSettings(bank_byte_alignment= 256*1024//4) # <-----
)
Write speed: 252.3MiB/s
Read speed: 424.6MiB/s
``` 
When set to 0 (default value) it will not interfer with the previous behaviour of address_mapping     = …
=> litedram/address_mapping Add bank_byte_alignment

litedram/frontend/dma.py
Was reworked in a previous commit and rsv_level didn't survive
=> frontend/dma.py: Remove left-over rsv_level documentation

litedram/gen.py
Closes #334 
As far as I can tell, the axi port generation also assumes size 3, so hopefully this is the right fix
=> Fix AxSIZE

litedram/phy/s7ddrphy.py
These operations aren't supported for DDR2 memories.
Fixes https://github.com/litex-hub/litex-boards/pull/658
Requires https://github.com/enjoy-digital/litex/pull/2238
=> phy/s7ddrphy.py: disables write_leveling,write_dq_dqs_training,write_latency_calibration when memtype == DDR2
